### ISSUE TITLE
Retry segment causes application to fail

### ISSUE THREAD

**Issue by ronald-wentworth** [simonrob/email-oauth2-proxy#189]
Hey not a python developer but am using your email proxy program.  We ran into an issue where the invalid token exception would retry and fail.  Needed to restart to recover.  I removed the retry functionality contained in and we no longer seem to have the issue.
The following is the error we would receive after a retry attempt.

Email OAuth 2.0 Proxy Local server auth mode: please authorise a request for account rtoc@moblize.com
2023-08-22 15:52:43: Local server auth mode (localhost:6767): unable to start local server. Please check that `redirect_uri` for rtoc@moblize.com is unique across accounts, specifies a port number, and is not already in use. See the documentation in the proxy's sample configuration file. OSError(98, 'Address already in use')

We are running in non-qui mode.

**Comment by ronald-wentworth** [comment]
Ok we still had the issue it just occurred later.

**Comment by ronald-wentworth** [comment]
My concern with the code is that the close looks to dereference not actually end the connection especially if an error were to occur during the close. If you need further information I can provide you whatever you need.

**Comment by simonrob** [comment]
Thanks for reporting this – at the moment I'm not quite sure which retry functionality you are referring to, because the error message you've posted relates to local server mode. Do you mean when an authentication request fails, for example due to being rejected by the user?

It would be useful if you could point to exactly where you think the issue is being caused and what you've changed.

Also, could you clarify whether you are using the [issue-183 branch](https://github.com/simonrob/email-oauth2-proxy/tree/issue-183), which separates out the token error from other connection issues?

**Comment by simonrob** [comment]
Thanks for reporting this – at the moment I'm not quite sure which retry functionality you are referring to, because the error message you've posted relates to local server mode. Do you mean when an authentication request fails, for example due to being rejected by the user?

It would be useful if you could point to exactly where you think the issue is being caused and what you've changed.

Also, could you clarify whether you are using the [issue-183 branch](https://github.com/simonrob/email-oauth2-proxy/tree/issue-183), which separates out the token error from other connection issues?

**Comment by ronald-wentworth** [comment]
We are using thead safe branch because we were getting config corruption when we got this error and had to redeploy.  The retry I'm talking about is the retry in the
        except InvalidToken as e:
block

**Comment by simonrob** [comment]
Thanks – it's worth trying the concurrent branch that you are using in conjunction with the issue-183 branch because that separates out the token error in a different way. Could you try the [issue-189 branch](https://github.com/simonrob/email-oauth2-proxy/tree/issue-189), which merges the two? (I intend to merge both of these into the main project anyway once the original reporters are able to test)

**Comment by ronald-wentworth** [comment]
We did try 183.  Got the following error.
23-08-24 19:47:21: Retrying login due to exception while decrypting OAuth 2.0 credentials for rtoc@moblize.com (invalid password): InvalidToken()
Retrying login due to exception while decrypting OAuth 2.0 credentials for rtoc@moblize.com (invalid password): InvalidToken()

**Comment by ronald-wentworth** [comment]
The token works again after restart.

**Comment by simonrob** [comment]
Have you set `delete_token_on_password_error` to `False`? And are you using multiple clients at once perhaps? I suspect you have one client with the right password and another with the wrong one, which could cause this error.

**Comment by ronald-wentworth** [comment]
Yes there are multiple clients.  I'll try the delete_account_token_on_password_error to false.  Even if this was the case we should get a good one the next time the correct password is sent.  But by this time the entire connection is gone and we get the above port error.

**Comment by simonrob** [comment]
The port error is explained in the documentation - local server mode is an extra feature to support situations where interactive authentication is not possible. Improvements are welcome if you spot another way to handle this, but it's a bonus capability rather than the core focus for the proxy.

It's fine to use multiple clients at the same time, but they do all need to use the correct password.

**Comment by simonrob** [comment]
Did you resolve this? I'll close the issue if so.

**Comment by ronald-wentworth** [comment]
No we're still having issues.  We're still trying to identify if this could be email password related.  We haven't found 1 yet.

**Comment by simonrob** [comment]
Were you able to make any progress here?

**Comment by simonrob** [comment]
I intend to close this issue in the next few days under the assumption that it has been resolved, but just let me know if that's not the case.

**Comment by ronald-wentworth** [comment]
So I think the issue is still there in the retry code.  You did mention that this was "enhancement" feature but it looks like if you're running headless and an auth fails the application will stop working.  So at least I would recommend something that bypasses this route.

**Comment by simonrob** [comment]
Thanks for following up. I may be completely missing something here, but I don't see how the retry can cause the proxy to fail. The proxy closes the local server after finishing using it (whether successful or failed), and even if this is for whatever reason not happening properly, you can reconnect the client (perhaps after a short wait for the socket to be cleared up).

How can I replicate this to look into it? And what am I missing that means your setup doesn't close the local authentication server?

**Comment by Mrstaubsauger** [comment]
Hello, 
i have got the same problem. 
"Retrying login due to exception while decrypting OAuth 2.0 credentials for abc@abc.com (invalid password): InvalidToken()"
The problem occurs only with one account connection to outlook, any other account works fine. The Password is definetely correct. I have already tested it with some new created accounts and as i said, everyone works, except this one. But this one, even after deleting and recreating with exact the same properties as newly created (except the name) will always give this error. 
I came to use your E-Mail-Proxy after failing with DavMail, which also had problems with connecting to this specific account. 
The problem also only occurs with sending mails with SMTP. When catching via IMAP it works fine, but when i try to send an email it directly gives the error and wants to reauthorize. 
The first try after authorizing mostly works, but when when attempting to send another mail, error occurs.

I tried setting 
 if AppConfig.get_global('delete_account_token_on_password_error', fallback=true)
to false, but it didnt work. 

Any other approaches?

**Comment by simonrob** [comment]
Interesting that you say it only happens for SMTP. Are you 100% sure that your client is using the same password for SMTP and IMAP?

I will need to see a proxy log (in `--debug`) mode to look further into this – please could you provide one?

> I tried setting
> if AppConfig.get_global('delete_account_token_on_password_error', fallback=true)
> to false, but it didnt work.

To be clear, you change the value of `delete_account_token_on_password_error` in the config file, rather than editing that code. Is that what you're doing?

**Comment by simonrob** [comment]
Thanks – this is really useful. Two things to follow up on:

1) What SMTP client are you using? The IMAP log is from Thunderbird 102.15.1. I'm assuimg that this is also what you are using for SMTP, but could you confirm?

2) Please download [this version](https://github.com/simonrob/email-oauth2-proxy/tree/issue-189) of the proxy script, and edit [line 126](https://github.com/simonrob/email-oauth2-proxy/blob/42d75aeb7125278d07c17d54d168aeee8eb9cb05/emailproxy.py#L126) to be `CENSOR_CREDENTIALS = False`. Note: **this will cause the proxy to print your username and password to the console** instead of the `[[ Credentials removed from proxy log ]]` message.

I need you to check that, firstly, the same values are printed for both IMAP and SMTP (to make sure you don't have, say, an old SMTP password cached in your client). Based on your log above, the relevant values in the debug log after this change should be something like:

- IMAP: 
```
2023-09-14 11:06:35: IMAP ([::]:143; [::ffff:127.0.0.1]:51521->outlook.office365.com:993) --> b'83 authenticate PLAIN\r\n'
2023-09-14 11:06:35: IMAP ([::]:143; [::ffff:127.0.0.1]:51521->outlook.office365.com:993) <-- b'+ \r\n'
2023-09-14 11:06:35: IMAP ([::]:143; [::ffff:127.0.0.1]:51521->outlook.office365.com:993) --> b'AGVtYWlsQGV4YW1wbGUuY29tAHBhc3N3MHJk\r\n'
```

- SMTP:
```
2023-09-14 11:08:25: SMTP ([::]:25; [::ffff:127.0.0.1]:51596->smtp.office365.com:587) --> b'AUTH PLAIN AGVtYWlsQGV4YW1wbGUuY29tAHBhc3N3MHJk\r\n'
```

It is critical that the output after the connection details and IMAP/SMTP commands is character-for-character identical in both cases (the `AGVtYWlsQGV4YW1wbGUuY29tAHBhc3N3MHJk` in my example). If these values do not match, then either you have a different password set up in your client for IMAP vs. SMTP; or, there is another variant of the `PLAIN` authentication method that the proxy is not accounting for.

If the values *are* identical, and you can provide me with the actual values you see here (perhaps after changing your password in your client to something temporary) then all the better.

**Comment by Mrstaubsauger** [comment]
You are right!! There are two different passwords! 
The IMAP Password is the current one and the SMTP Password is the old one. Very mysterious. 
But your proxy works fine and did the right thing. Nothing to do for you here anymore =) 
If you have any quick tips regarding Microsoft Exchange Online SMTP and IMAP password management or similar advice, I'm certainly open to them. Otherwise, the issue is resolved from my end (and maybe it helps the original poster).
Thanks!

**Comment by simonrob** [comment]
Thanks for following up and confirming this – I'm glad this turned out to be on the client side rather than an issue with the proxy.

I'll merge the minor changes from this branch and add documentation about the fact that many clients (mostly for historical reasons) support different passwords for POP/IMAP and SMTP, and that it is important to be sure that these are identical.

In terms of tips for password management, it's worth reiterating that the password used by your client with the proxy does *not* need to be the same as your actual account password, so you can perhaps manage this using a different approach. Conversely, if you *want* to use the same password for both the proxy and your actual account, this is also okay. Whatever works best for you.
